package yingyongzimodel

type Yingyongzi struct {
	Shuzu           string
	Appglobal       string
	Shujukuip       string
	Xiahuaxian      string
	Baseutils       string
	Maohao          string
	InsertMulti     string
	Juesequanxian   string
	Xinxibianma     string
	Yu              string
	Dianhao         string
	Dakuohaoyou     string
	Tiaoshu         string
	Allerrors       string
	YingwenError01  string
	Mingcheng       string
	Maintest        string
	Dakuohaozuo     string
	Baifenhao       string
	Services        string
	Zhongkuohaozuo  string
	Shi             string
	Jinghao         string
	Youxiao         string
	Youxiang        string
	Dayuhao         string
	Wuxiao          string
	Shujuku         string
	Appinits        string
	Baseglobal      string
	Jwtyan          string
	Yingyongzimodel string
	Apputils        string
	Fanxiexian      string
	Jiahao          string
	Leixing         string
	Yuyan           string
	Shujukumima     string
	Xiaokuohaozuo   string
	Insert          string
	Biao            string
	Xinxi           string
	Zhi             string
	Quanxianbianma  string
	Appmodels       string
	Views           string
	Zhongwen        string
	Qiehao          string
	Xieyihttp       string
	Github          string
	Lie             string
	Basemodels      string
	Conf            string
	Static          string
	Chengfanghao    string
	Wenzi           string
	Tianjiaduoge    string
	Xiugaiyige      string
	Baseinits       string
	Ormdebug        string
	ZhongwenError02 string
	Changdu         string
	Shanchuyige     string
	Id              string
	Shezhi          string
	Chaxunyige      string
	Gantanhao       string
	Huanhangfu      string
	Yizuobian       string
	Douhao          string
	Hanfuxin        string
	Konggefu        string
	Xinxijuese      string
	Duankou         string
	Baserun         string
	Controllers     string
	Wenhao          string
	Jichu           string
	Juese           string
	Biaoji          string
	Routers         string
	Xiaoyuhao       string
	Fenhao          string
	Read            string
	Fou             string
	Xieyitcp        string
	Delete          string
	Quanxian        string
	Mulu            string
	Update          string
	Shujukuduankou  string
	Shujukuyonghu   string
	ZhongwenError01 string
	Zhongkuohaoyou  string
	Meiyuanfu       string
	Xinghao         string
	Hanfuxinormer   string
	Dengyuhao       string
	Danyinhao       string
	YingwenError02  string
	Jianhao         string
	Yanzheng        string
	Juesebianma     string
	Jwtmima         string
	Lujing          string
	Tests           string
	Fuhao           string
	Shuangyinhao    string
	Wangluo         string
	Default         string
	Yanzhengleixing string
	Yingwen         string
	Bolanghao       string
	Bianma          string
	Shujukuqudong   string
	Quana           string
	Daos            string
	Xiexian         string
	Huozhehao       string
	Tianjiayige     string
	Xiaokuohaoyou   string
}
