package yingyongzimodel

type Yingyongzi struct {
	Changdu         string
	Juesequanxian   string
	Appinits        string
	YingwenError01  string
	Xieyihttp       string
	Biao            string
	Shujukuqudong   string
	Yingwen         string
	Huozhehao       string
	Jianhao         string
	Appmodels       string
	Baseinits       string
	Basemodels      string
	Qiehao          string
	Shuangyinhao    string
	Maintest        string
	Maohao          string
	Lie             string
	Leixing         string
	Xiaokuohaoyou   string
	Douhao          string
	Juesebianma     string
	Yu              string
	YingwenError02  string
	Dianhao         string
	Shi             string
	Static          string
	Duankou         string
	Bolanghao       string
	Xiexian         string
	Konggefu        string
	Default         string
	Fuhao           string
	Xiahuaxian      string
	Meiyuanfu       string
	Wenzi           string
	Zhi             string
	Baseutils       string
	Baseglobal      string
	Shujukumima     string
	Baserun         string
	Bianma          string
	Id              string
	Biaoji          string
	ZhongwenError01 string
	Xiaokuohaozuo   string
	Xinxi           string
	Dayuhao         string
	Xiaoyuhao       string
	Wenhao          string
	Yizuobian       string
	Fou             string
	Yanzhengleixing string
	Yuyan           string
	Fanxiexian      string
	Jinghao         string
	Jichu           string
	Youxiao         string
	Yanzheng        string
	Dengyuhao       string
	Fenhao          string
	Hanfuxin        string
	Github          string
	Shujukuduankou  string
	Services        string
	Yingyongzimodel string
	Quanxian        string
	Lujing          string
	Apputils        string
	Appglobal       string
	Jiahao          string
	Danyinhao       string
	Allerrors       string
	Shezhi          string
	Shujukuyonghu   string
	Chengfanghao    string
	Jwtmima         string
	Routers         string
	Dakuohaoyou     string
	Baifenhao       string
	Xinghao         string
	Mingcheng       string
	Xinxibianma     string
	Shujuku         string
	Mulu            string
	Tests           string
	Quana           string
	Jwtyan          string
	Ormdebug        string
	Zhongwen        string
	Zhongkuohaozuo  string
	Controllers     string
	Xieyitcp        string
	Shujukuip       string
	Gantanhao       string
	Zhongkuohaoyou  string
	Wuxiao          string
	Conf            string
	Quanxianbianma  string
	Huanhangfu      string
	Xinxijuese      string
	Tiaoshu         string
	Daos            string
	Views           string
	Juese           string
	Youxiang        string
	ZhongwenError02 string
	Dakuohaozuo     string
	Wangluo         string
}
