package appmodels

type Yingyongzi struct {
	Dianhao         string
	Fou             string
	Wuxiao          string
	Yanzheng        string
	Mingcheng       string
	Appinits        string
	Static          string
	Bolang          string
	Juesequanxian   string
	Leixing         string
	Wenzi           string
	Fanxiexian      string
	Jichu           string
	Lie             string
	Yu              string
	Baserun         string
	Gantanhao       string
	Xiexian         string
	Kongge          string
	Id              string
	Mulu            string
	Apputils        string
	Routers         string
	Fuhao           string
	Maintest        string
	Shezhi          string
	Youxiao         string
	Quanxian        string
	Xinxi           string
	Yanzhengleixing string
	Lujing          string
	Youxiang        string
	Xieyihttp       string
	Zhi             string
	Appmodels       string
	Shi             string
	Github          string
	Basemodels      string
	Zhongkuohaozuo  string
	Xiaoyu          string
	Biao            string
	Duankou         string
	Zhongkuohaoyou  string
	Quanxianbianma  string
	Shujuku         string
	Baseutils       string
	Tests           string
	Hanfuxin        string
	Xiaokuohaoyou   string
	Juese           string
	Biaoji          string
	Conf            string
	Controllers     string
	Xiahuaxian      string
	Wangluo         string
	Xinxijuese      string
	Xiaokuohaozuo   string
	Juesebianma     string
	Baseinits       string
	Daos            string
	Views           string
	Dakuohaoyou     string
	Dayu            string
	Xinxibianma     string
	Services        string
	Huanhang        string
	Bianma          string
	Dakuohaozuo     string
}
